# Generated by Django 5.0 on 2023-12-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cupcake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flavor", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("size", models.TextField()),
                ("image", models.TextField()),
            ],
        ),
    ]
